### PR TITLE
[FEATURE] [MER-3600] Migrate Review liveview

### PR DESCRIPTION
**Pull request by simonchoxx**
[MER-3600](https://eliterate.atlassian.net/browse/MER-3600)

This PR migrates the `Review` liveview to be accessible from the new menu for the course author workspace.

In addition to the liveview, the necessary components used by the main liveview are migrated, as well as the existing logic tests.

https://github.com/user-attachments/assets/6d5935e7-3901-4860-9216-b8c84670b800

[MER-3600]: https://eliterate.atlassian.net/browse/MER-3600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by eliknebel** [comment]
Screenshot 2024-08-29 at 4 49 01 PM

While trying to test out these changes, I am seeing this error message, I'm not sure if its related or not

**Comment by simonchoxx** [comment]
@eliknebel I have not received such an error message while working on the ticket. As far as I can see the error is occurring in the sidebar component and I don't think it would have anything to do with the liveview I worked on. 
Have you tried more than one project?

**Comment by simonchoxx** [comment]
@eliknebel We did some research with @nicocirio and @Francisco-Castro about this error and it seems we have a bug that we need to fix in that `set_sidebar` plug. 
Maybe we could address this error in another ticket. 
I think that by deleting the cookies and restarting the server you should stop seeing the error.

**Review by eliknebel — APPROVED** [review]

**Comment by eliknebel** [comment]
Filed a followup ticket for the set_sidebar issue. https://eliterate.atlassian.net/browse/MER-3715

**Pull request merged**
