### PR TITLE
[FEATURE] Legacy Custom Drag and Drop support

### PR DESCRIPTION
**Pull request by darrensiegel**
This PR implements a new activity type: the "Custom" Drag and Drop activity.  This activity allows the very custom legacy OLI activities that provide custom CSS and HTML to be authored and delivered in Torus. 

I still need to:

- [x] Add unit tests for the new reset part infrastructure
- [x] Address an issue where hints cannot be added in authoring
- [x] Test cross browser testing of the core drag and drop impl

### CODE REVIEW

**Review by rgachuhi — CHANGES_REQUESTED** [review]
If I simply add the default dnd activity on a page without modifications, I see the following errors on the browser console when I try previewing the page or accessing the page on delivery. Both fail to show the dnd activity.

`The above error occurred in the <StemDeliveryConnected> component:

StemDeliveryConnected@https://raffapp.ngrok.io/js/oli_custom_dnd_delivery.js:8849:133
div
div
CustomDnDComponent@https://raffapp.ngrok.io/js/oli_custom_dnd_delivery.js:8999:91
DeliveryElementProvider@https://raffapp.ngrok.io/js/oli_custom_dnd_delivery.js:8373:5
Provider@https://raffapp.ngrok.io/js/oli_custom_dnd_delivery.js:24295:15

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
`

**Comment by darrensiegel** [comment]
Hmmm, I just tested this w/ Firefox and I do not see the above issue.  After checking out the `custom-dnd` branch, did you do a `mix ecto.reset` ?  This is required given that this branch introduces a new activity.

**Comment by rgachuhi** [comment]
> 

Still no luck on my part. Hitting the same problem even after I do a full reset.

**Comment by darrensiegel** [comment]
Okay, I believe I tracked down and fixed the problem.  @rgachuhi Can you pull the latest and try this again?

**Comment by rgachuhi** [comment]
> Okay, I believe I tracked down and fixed the problem. @rgachuhi Can you pull the latest and try this again?

Your changes fixed the issue. I am now able to preview

>

**Review by rgachuhi — APPROVED** [review]

**Pull request merged**
