### PR TITLE
[MER-2953] Upgrade user edit form to be a form component

### PR DESCRIPTION
**Pull request by Francisco-Castro**
Ticket: [MER-2953](https://eliterate.atlassian.net/browse/MER-2953)

This PR upgrades the form used to change user information from an admin account. The advantage of this upgrade is that now the admin get immediate feedback the interacting with the form and something goes wrong, like having an empty field.

The `update_changeset_for_admin` changeset was also changed to avoid extra casting.

[MER-2953]: https://eliterate.atlassian.net/browse/MER-2953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nicocirio — COMMENTED** [review]
This looks great ❤️ ! I think the error messages beside the corresponding input are much more clear than the error flash message.
I've been playing around with the form and I *might* have found a bug (not 100% sure). Should an admin be allowed to change a student email to an already existing email (used by another independent learner) if the current student is not an independent learner?
In the following example `student3@test.com` has already been taken by another independent learner, and I want to use the same email but for a non independent learner

https://github.com/Simon-Initiative/oli-torus/assets/74839302/5d5d4f39-2b3c-42ab-91f9-08990ba2ef68

**Comment by Francisco-Castro** [comment]
Thanks @nicocirio for taking a look a this PR. 🙏 Watching the video it looks like a bug. I'll take a look at it a get back to you.

**Comment by Francisco-Castro** [comment]
@nicocirio Could you please take another look at this PR at your convenience? I added some [tests](https://github.com/Simon-Initiative/oli-torus/pull/4608/commits/792b28e252e63fd31ffa22d82dfeaad99b5386ad) to the `update_changeset_for_admin` changeset.

**Review by nicocirio — APPROVED** [review]

**Review by eliknebel — APPROVED** [review]
tested, work as expected

**Pull request merged**
