### PR TITLE
[CHORE] Upgrade to elixir 1.12

### PR DESCRIPTION
**Pull request by eliknebel**
This PR upgrades elixir to 1.12 and phoenix to 1.5.9. To upgrade locally:

1. Upgrade elixir (e.g. `brew upgrade elixir` or using [asdf](https://asdf-vm.com/#/))
2. run `mix local.rebar`
3. `mix clean && mix deps.clean --all && mix deps.get`

### CODE REVIEW

**Comment by eliknebel** [comment]
Some unit tests are broken and need fixed, this will require changing lti_1p3 lib

**Comment by darrensiegel** [comment]
Do the above instructions for locally upgrading Elixir also bump Erlang/OTP to version 24?

**Comment by eliknebel** [comment]
Yes, I believe so
```
$ elixir -v
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.12.0 (compiled with Erlang/OTP 22)
```

**Comment by darrensiegel** [comment]
I ran into some trouble following the above instructions.  I got into a state where invoking mix commands resulted in a collection of the following error:

```
12:13:56.332 [error] Task #PID<0.159.0> started from :hex_fetcher terminating
** (UndefinedFunctionError) function :ssl.cipher_suites/1 is undefined or private
    (ssl 10.4) :ssl.cipher_suites(:openssl)
    (hex 0.20.5) lib/hex/http/ssl.ex:124: Hex.HTTP.SSL.filter_ciphers/1
    (hex 0.20.5) lib/hex/http/ssl.ex:66: Hex.HTTP.SSL.ssl_opts/1
    (hex 0.20.5) lib/hex/http.ex:41: Hex.HTTP.build_http_opts/2
    (hex 0.20.5) lib/hex/http.ex:16: Hex.HTTP.request/5
    (hex 0.20.5) lib/hex/registry/server.ex:306: anonymous fn/3 in Hex.Registry.Server.prefetch_online/2
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.0) lib/task/supervised.ex:35: Task.Supervised.reply/5
Function: #Function<17.86168715/0 in Hex.Registry.Server.prefetch_online/2>
    Args: []
```

The resolution seemed to be to do `mix local.hex` and then `mix local.rebar` prior to running `mix clean && mix deps.clean --all && mix deps.get`

**Review by darrensiegel — APPROVED** [review]

**Pull request merged**
